
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Buid and Compile
      run: mvn compile
  Security_Check:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
    - uses: actions/checkout@v4
    - name: Trivy installation
      run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
    - name: Trivy FS scan
      run: trivy fs --format table -o fs-report.json .
    - name: Gitleasks Installation
      run: sudo apt install gitleaks -y
  Test:
    runs-on: ubuntu-latest
    needs: Security_Check
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven Test
      run: mvn test
       
    
      
    

      
    

    
    

  
